### ISSUE TITLE
$

### ISSUE THREAD

**Issue by unreaIuser** [kejsik/Fortnite-External-SelfLeak#1]
What's the point of self-leaking your super ud paste, if you don't even include all the files. Useless post.

**Comment by unreaIuser** [comment]
You will never make ANY money from github scamming like dis, I doubt that your driver is undetected on any anti-cheat. Probably pasted and skidded from github like everything in this repository.

**Comment by kejsik** [comment]
its not about scamming bro there are a lot of files to include in this solution so I typed if I forgot something then they should dm me and my cheat is driverless :)
